Repository jfmengels/elm-review-simplify, pull requests merged in 2023-10, with the labels that each got.

#218 listFoldAnyDirectionChecks use emptiableFoldChecks
  src/Simplify.elm
  tests/SimplifyTest.elm
Labels: refactor

#224 Type properties use qualified fn instead of just the name
  src/Simplify.elm
Labels: refactor

#225 Add tuple access on tuple map simplifications
  CHANGELOG.md
  src/Simplify.elm
  tests/SimplifyTest.elm
Labels: enhancement

#227 More "on wrap always returns incoming" composition checks
  CHANGELOG.md
  src/Simplify.elm
  tests/SimplifyTest.elm
Labels: enhancement

#236 Make checkInfo argument implicit
  src/Simplify.elm
Labels: refactor

#240 Move internal elm-review rule into review/src
  elm-review-convert-qualified-to-from-fn-module/elm-review-package-tests/check-examples-were-updated.js
  elm-review-convert-qualified-to-from-fn-module/elm-review-package-tests/check-previews-compile.js
  elm-review-convert-qualified-to-from-fn-module/elm-review-package-tests/helpers/ansi.js
  elm-review-convert-qualified-to-from-fn-module/elm-review-package-tests/helpers/find-configurations.js
  elm-review-convert-qualified-to-from-fn-module/elm-tooling.json
  elm-review-convert-qualified-to-from-fn-module/elm.json
  elm-review-convert-qualified-to-from-fn-module/maintenance/MAINTENANCE.md
  elm-review-convert-qualified-to-from-fn-module/maintenance/update-examples-from-preview.js
  elm-review-convert-qualified-to-from-fn-module/package.json
  elm-review-convert-qualified-to-from-fn-module/preview/elm.json
  elm-review-convert-qualified-to-from-fn-module/preview/src/ReviewConfig.elm
  elm-review-convert-qualified-to-from-fn-module/review/elm.json
  elm-review-convert-qualified-to-from-fn-module/review/src/ReviewConfig.elm
  review/elm.json
  review/src/ConvertQualifiedToFromFnModule.elm
  review/tests/ConvertQualifiedToFromFnModuleTest.elm
Labels: refactor

#253 Correct Dict.partition simplifications
  CHANGELOG.md
  src/Simplify.elm
  tests/SimplifyTest.elm
Labels: bug

#262 List.all/any on list with unnecessary element simplifications
  CHANGELOG.md
  src/Simplify.elm
  tests/SimplifyTest.elm
Labels: bug, enhancement

#269 Add access record type alias constructor call simplification
  CHANGELOG.md
  src/Simplify.elm
  src/Simplify/AstHelpers.elm
  tests/Simplify/RecordAccessTest.elm
Labels: enhancement

#280 Add flatMap (f << wrap) check
  CHANGELOG.md
  src/Simplify.elm
  tests/Simplify/MaybeTest.elm
Labels: enhancement
